### ISSUE TITLE
Jiotv m3u

### ISSUE THREAD

**Issue by rehank3g** [mohd-baquir-qureshi/Acrotv#1]
Hi, 
Can you please share the script.to generate jiotv m3u.

**Comment by mohd-baquir-qureshi** [comment]
It's paid

**Comment by rehank3g** [comment]
How much?

**Comment by mohd-baquir-qureshi** [comment]
Please contact me at https://baquir.xyz

**Comment by rehank3g** [comment]
I want to purchase.. please let me know the price

**Comment by rehank3g** [comment]
Please let me know the price?

**Comment by rehank3g** [comment]
NA
